# Usage:
# docker-compose build && docker-compose up
version: '3.2'

services:
  nginx:
    image: nginx:stable
    depends_on:
      - grocy
    ports:
      - '80:80'
    volumes_from:
      - grocy
    volumes:
      - ./grocy.conf:/etc/nginx/conf.d/default.conf

  grocy:
    image: sstamoulis/grocy
    build:
      context: .
    expose:
      - 9000
    volumes:
      - database:/www
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
      GROCY_CULTURE: en

volumes:
  database:
